### ISSUE TITLE
Search for the next time two bodies reach a target relative ecliptic longitude

### ISSUE THREAD

**Issue by cosinekitty** [cosinekitty/astronomy#101]
Write a function that is given two different, non-Earth bodies and a start time. It then finds the next time both bodies reach a given difference of geocentric ecliptic longitude. If I do this right, the code won't grow very much in size because I can rework `MoonPhase` to call this function.

**Comment by matheo** [comment]
This sounds amazing :)

**Comment by cosinekitty** [comment]
@zohozer Take a look at the [lunar_angles.py](https://github.com/cosinekitty/astronomy/blob/master/demo/python/lunar_angles.py) demo script for an example of how to search for when the Moon and another body (Sun or planet) forms a multiple of a 30 degree ecliptic longitude angle as seen from the Earth. I hope this is helpful for you. I will start working on the constellation transition search soon.
