### ISSUE TITLE
Project logo artwork

### ISSUE THREAD

**Issue by cosinekitty** [cosinekitty/astronomy#113]
It would be nice to have a logo designed for Astronomy Engine. Find someone with some artistic talent to help!

**Comment by offsky** [comment]
If you are willing to pay for it, I have had good results finding talented artists on fiverr.com. You could get a good logo for $20

**Comment by cosinekitty** [comment]
Yes, I am willing to pay. Do you have any tips for finding artists on fiver?

**Comment by offsky** [comment]
I do a search for what I am looking for and then browse through the portfolios of artists and "heart" the ones I like. Then I do a deeper dive into each one and rank them. It takes some time.  Then I message them with what I want and see if they respond timely and with good english and if it sounds good I go for it.  Its usually so cheap that if I don't like the result I can just order again from someone else. I got my logos for puzzletales.com and foldnfly.com from fiverr

**Comment by offsky** [comment]
A slightly more expensive option ($300) is 99designs.com where you get multiple designers submitting designs and you get to pick your favorite.

**Comment by cosinekitty** [comment]
Thanks, Jake! That is the kind of practical help I wanted. I looked at your websites. I like your logos. You have quite a portfolio of online work! Pretty neat stuff with puzzles and paper airplanes.

**Comment by offsky** [comment]
Glad to help, and thanks for the compliment 😄 
I looked at your website too and saw a lot of common interests (rubiks cube, mandelbrot sets, sudoku, etc). We like the same things!

**Comment by offsky** [comment]
Here is another idea. I found these fantastical planet images while working on my project. I thought they were pretty cool. Maybe you could use one as your logo?

https://www.shutterstock.com/image-vector/vector-set-cartoon-planets-colorful-isolated-15430596
<img width="671" alt="Screen Shot 2021-11-24 at 12 40 55 PM" src="https://user-images.githubusercontent.com/1110926/143310066-59439414-eb70-485c-87ef-04005288136d.png">
98

**Comment by cosinekitty** [comment]
Those are nice images, but I have something specific in mind that I want to have custom made. I'm bouncing around a few ideas that I want to discuss with potential artists. Thanks for letting me know though!

**Comment by cosinekitty** [comment]
I ended up using the Wix logo builder. Later I may come back and hand this off to a real artist to improve, but it's good enough for now.
