### ISSUE TITLE
Eliminate use of Julian Dates

### ISSUE THREAD

**Issue by cosinekitty** [cosinekitty/astronomy#13]
Julian Dates reduce precision by consuming so many mantissa bits. Rework to use days since 2000 (or 1900, or MJD=1857-11-17?), which is closer to the center of my eventual range of supported years (1600..2200).

**Comment by matheo** [comment]
Does this means that I cannot get realiable data of my birthdate? or what does this imply please

**Comment by cosinekitty** [comment]
This change (d01ac8e1506bd88fd415e5b53a5bf5b1a1a1a622) did not reduce functionality for users of the library. It just made the internal calculations more accurate.
