### ISSUE TITLE
Calculate Moon's rotation?

### ISSUE THREAD

**Issue by ebraminio** [cosinekitty/astronomy#144]
Sorry if this is addressed already, for a non-profit free and opensource app that doesn't have access to internet I want to be able to draw moon angle based on the user location. Is that already possible to calculate this using algorithms here? See for example moon shape rotation of https://www.timeanddate.com/astronomy/finland which is different from https://www.timeanddate.com/astronomy/china/beijing 

Thanks :)

**Comment by cosinekitty** [comment]
Are you asking about which direction the sunlit side of the Moon faces, using the local observer's horizon? If so, try taking a look at one of the "camera" demos:

- [Camera demo in C](https://github.com/cosinekitty/astronomy/blob/master/demo/c/camera.c)
- [Camera demo in C#](https://github.com/cosinekitty/astronomy/blob/master/demo/csharp/camera/camera.cs)
- [Camera demo in JavaScript](https://github.com/cosinekitty/astronomy/blob/master/demo/nodejs/camera.js)
- [Camera demo in Python](https://github.com/cosinekitty/astronomy/blob/master/demo/python/camera.py)

Below is an example of running the C version on my own system. I think you are most interested in the line that starts with "Tilt angle of sunlit side".

```
don@spearmint:~/github/astronomy/demo/c $ ./camera
USAGE: ./camera [-e | latitude longitude] [yyyy-mm-ddThh:mm:ssZ]

If '-e' is specified, an environment variable must be set as follows:
ASTRONOMY_ENGINE_OBSERVER='latitude longitude'
Otherwise, the latitude and longitude must appear in the command line.

don@spearmint:~/github/astronomy/demo/c $ ./camera +30.5 -91.5
Moon horizontal position: azimuth = 235.557, altitude = 27.631
Moon check: x = 1.0000e+00, y = -2.8073e-16, z = -4.5348e-16
Sun vector: x = 0.534278, y = -0.337031, z = -0.753647
Tilt angle of sunlit side of the Moon = -114.094 degrees counterclockwise from up.
Moon magnitude = -8.73, phase angle = 122.01 degrees.
Angle between Moon and Sun as seen from Earth = 57.88 degrees.
```

**Comment by ebraminio** [comment]
Oh so it is there, let me close this, thanks :)

**Comment by ebraminio** [comment]
It might be interesting of the app I want to use this

https://user-images.githubusercontent.com/833473/148596509-c5d621ec-fe24-4f98-8f7f-ecb1dbf7b440.mov

So I've ported some port of the code to https://github.com/persian-calendar/DroidPersianCalendar/commit/864ecda839c102a9931ebf6730e65a874f8aa5a1

But it isn't yet hooked as my other algorithms don't match with that code needs yet and now I see moon tilt might not that suits well for days change animation still. Btw you might like this part of the app also,

https://user-images.githubusercontent.com/833473/148596866-843407b0-7daf-4ba6-95c9-dc994cb13dd2.mov

it doesn't use this codebase's algorithms but guess you still might like it :)

**Comment by cosinekitty** [comment]
That is cool! I also have support for calculating what constellation any point in the sky occupies, if you are interested in that.

**Comment by ebraminio** [comment]
Oooh nice, somehow the app needs share a lot with what this library offers, see for example,

https://user-images.githubusercontent.com/833473/148642966-d57b60ab-543f-470d-bae2-7ff4bc4046b7.mov

Equinox calculations, moon phase status, sunset sunrise times also were needed and are implemented/ported for a long time and there was a recent eclipse calculations also. The FOSS app is released since 2012 and have over millions installations and essentially needed for the local as the lack of OS support of the calendars.
