### ISSUE TITLE
Support for Dart Language

### ISSUE THREAD

**Issue by moosalim** [cosinekitty/astronomy#157]
Hello

Can you please add support to Dart

**Comment by cosinekitty** [comment]
Hi @moosalim . Welcome to the project. Would you be willing to add this to the [programming language discussion](https://github.com/cosinekitty/astronomy/discussions/109)? I am not familiar with Dart, so it would help me to post there about:
- What platform(s) Dart would enable that can't be met with the existing languages.
- Would you be available to help solve problems with Dart, like best practices, distributing packages, etc?

**Comment by moosalim** [comment]
Hi @cosinekitty 

sure I will post it there and give highlight on both points

**Comment by cosinekitty** [comment]
(Moved conversation to discussion #109 ).
