### ISSUE TITLE
Use hypot

### ISSUE THREAD

**Issue by ebraminio** [cosinekitty/astronomy#158]
Some of the targeted languages have https://www.w3schools.com/python/ref_math_hypot.asp

`hypot(x, y ...) = sqrt(x*x + y*y ...)`

And in [here](https://github.com/cosinekitty/astronomy/blob/2eec19fc23465bf18f38c1dd289edaac35907b3c/demo/python/triangulate.py#L56) it can be used, just wanted to share this minor thing with you :)

**Comment by cosinekitty** [comment]
I like that. I will look into it.

**Comment by cosinekitty** [comment]
One issue I ran into: the supported version of Python on Debian Buster (which I still use on one of my home systems) is 3.7.3, whose `math.hypot` requires exactly 2 parameters. The generalized `math.hypot` requires Python 3.8+. Buster's [end of life](https://wiki.debian.org/DebianReleases) is estimated to be August 2022, but there may be other operating systems with older Python versions. For now, I am reluctant to break compatibility for anyone. (It would also mean I would have to upgrade my own system to Bullseye, LOL.)

**Comment by ebraminio** [comment]
Oh sure, tbh I found this in jvm and used on my codes and then learnt about its existence elsewhere, apparently it exists in C standard library also for example.

**Comment by ebraminio** [comment]
Looks just fantastic, thank you so much 🙏🙏🙏

**Comment by ebraminio** [comment]
Also if C# code now has become a bit inconsistent and about the particular python issue, I think someday we can implement our own polyfill in .NET and other implementations.
