### ISSUE TITLE
No module named 'astronomy' Win 10 Py 3.10

### ISSUE THREAD

**Issue by miklosnemeth** [cosinekitty/astronomy#169]
After pip install astronomy-engine cannot import astronomy module.

D:\Python310\Lib\site-packages\astronomy_engine-2.0.13.dist-info\ exist but no astronomy folder

**Comment by cosinekitty** [comment]
Thank you for the report. I will investigate.

**Comment by cosinekitty** [comment]
@miklosnemeth Would you try upgrading to version 2.0.15 and try again? Please let me know whether that solves the problem.

**Comment by cosinekitty** [comment]
Update: please try 2.0.16. I realized I was accidentally exposing private symbols in 2.0.15. Only the intended public symbols should be visible in 2.0.16.

**Comment by miklosnemeth** [comment]
> Update: please try 2.0.16. I realized I was accidentally exposing private symbols in 2.0.15. Only the intended public symbols should be visible in 2.0.16.

2.0.16 works fine. Thx :)
