### ISSUE TITLE
Kotlin docs: fix links from docstrings to functions, types, etc.

### ISSUE THREAD

**Issue by cosinekitty** [cosinekitty/astronomy#179]
The Kotlin docstrings now contain stuff like this:

```
/**
 * Returned by #Astronomy.searchTransit or #Astronomy.nextTransit to report
 * information about a transit of Mercury or Venus.
 */
```

The `#funcName` syntax does not cause Dokka to generate links the way I want. Figure out how to fix this so I can express hyperlinks inside the Markdown docs.

**Comment by ebraminio** [comment]
According to https://kotlinlang.org/docs/kotlin-doc.html#links-to-elements

`Returned by [Astronomy.searchTransit] or [Astronomy.nextTransit] to report` should work on it.

**Comment by cosinekitty** [comment]
Thanks! I will try that.

**Comment by cosinekitty** [comment]
The square bracket notation has been working well for a while now. Forgot to close this issue until now.
