### ISSUE TITLE
Create NuGet package for C# version

### ISSUE THREAD

**Issue by cosinekitty** [cosinekitty/astronomy#180]
Investigate how to create a NuGet package for the C# version of Astronomy Engine. If anyone has experience creating NuGet packages, I could use some help!

**Comment by ebraminio** [comment]
I have a package in nuget https://github.com/ebraminio/PInvokeSerialPort this was essential https://github.com/ebraminio/PInvokeSerialPort/blob/main/Package.nuspec part IIRC which is explained here also https://nuget-tutorial.net/en/tutorial/100001/create-nuget-package

**Comment by cosinekitty** [comment]
I will read that tutorial link. Thank you!

**Comment by cosinekitty** [comment]
Note to myself: the dotnet core command line tool provides the command [`dotnet pack`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack) to create a NuGet packet. I will need to create a project and/or solution for Astronomy Engine by itself.

**Comment by cosinekitty** [comment]
I just created my first attempt at a NuGet package for Astronomy Engine:
https://www.nuget.org/packages/CosineKitty.AstronomyEngine/2.1.2

Feedback, comments, and results of attempting to use it are all encouraged. Thanks in advance.

**Comment by cosinekitty** [comment]
Completed in e187707412255bc4873d219ffe594d9f00655978.
