### ISSUE TITLE
C++ wrapper

### ISSUE THREAD

**Issue by xtemp09** [cosinekitty/astronomy#183]
Thanks for writing and maintaining such a useful library. Is there any chance you will add C++ wrapper for it?

The library could be much simpler with `std::string`, `std::numeric_limits`, `std::optional` and `std::tuple`.

**Comment by cosinekitty** [comment]
Thank you for your kind words.

I’m certainly open to the idea of a C++ wrapper header file. Right now I’m involved with the lengthy effort to add Kotlin support. Once that is complete (probably a month or two from now), I will take a look at this. 

In the meantime, I’d be interested in continuing a discussion about it here in this issue. What are examples of things in the C version that modern C++ would make easier? Using std::string makes sense for formatting AstroTime as a string.

**Comment by xtemp09** [comment]
The idea was based on the fragment in demo:
```
void PrintTime(astro_time_t time)
{
    astro_status_t status;
    char text[TIME_TEXT_BYTES];

    status = Astronomy_FormatTime(time, TIME_FORMAT_SECOND, text, sizeof(text));
    if (status != ASTRO_SUCCESS)
    {
        fprintf(stderr, "\nFATAL(PrintTime): status %d\n", status);
        exit(1);
    }
    printf("%s", text);
}
```
I got used to this:
```
void PrintTime(const Astro::time_t &time)
{
	const Astro::formatted_time text = Astro::FormatTime(time, Astro::TimeFormat::Second);
	
	if (!text.isSuccessful())
	{
		std::cerr << "\nFATAL(PrintTime): status " << formatted_time.status << '\n';
		exit (EXIT_FAILURE);
	}
	std::cout << text.value(); //std::string
}
```
Of course, the most important here is namespaces and, possibly, exception handling. It's strange that the program fails to print time and exits.

I've reconsidered my point and now I find writing a wrapper as unnecessary. Addition of `std::string` is two lines of code, I can write the wrapper on my own.

I also had an idea of returning an array or a vector of Moon phases/Eclipses/Seasons, but it's several lines of code, it's irrelevant for this library.

**Comment by cosinekitty** [comment]
OK. I would still consider creating a wrapper if it makes a C++ programmer's life easier when using Astronomy Engine. Yes, it is strange to check for an error code and bail out like that. Generally speaking, a careful caller to `Astronomy_FormatTime` doesn't need to check for errors. These demo programs also serve as unit tests (they are compiled and executed every time I push code to GitHub), so I am super paranoid to check for problems so I can catch them and fix them.
