### ISSUE TITLE
Jitpack build fails

### ISSUE THREAD

**Issue by ebraminio** [cosinekitty/astronomy#185]
JitPack runs this https://github.com/cosinekitty/astronomy/blob/kotlin/jitpack.yml and fails with this https://jitpack.io/com/github/cosinekitty/astronomy/94c7884f11/build.log

Let's see why so

**Comment by ebraminio** [comment]
Oh so those setup code can be put in https://github.com/cosinekitty/astronomy/blob/kotlin/jitpack.yml also.

**Comment by cosinekitty** [comment]
I think that will work, so long as the packing step occurs after the unit tests run. Is it possible to do it this way?

**Comment by cosinekitty** [comment]
Keep in mind, there will be a lot of required files, and they can be rather large in some cases.

**Comment by ebraminio** [comment]
apparently tests can be excluded like this https://stackoverflow.com/a/55727386

**Comment by cosinekitty** [comment]
Excluding all the tests would be fine with me, because the tests that I run on my local system, plus the same tests that run on GitHub Actions every time I push, will be plenty of testing. If you would like to submit a pull request for this, I would be grateful for the help!

**Comment by ebraminio** [comment]
Sure, I was going to do 😊
