### ISSUE TITLE
Kotlin: Astronomy.seasons crashes for numbers outside 1583..3667

### ISSUE THREAD

**Issue by ebraminio** [cosinekitty/astronomy#187]
The documentation of `Astronomy.season()` states `The value may be any integer, but only the years 1800 through 2100 have been validated for accuracy` but it actually fails if I issue `Astronomy.seasons(3668)` fails with:

```
Cannot find solution for Sun longitude 180.0
io.github.cosinekitty.astronomy.InternalError: Cannot find solution for Sun longitude 180.0
```

Or `Astronomy.seasons(1582)`
```
Cannot find solution for Sun longitude 0.0
io.github.cosinekitty.astronomy.InternalError: Cannot find solution for Sun longitude 0.0
```

Not that it matters much for me but say if user scrolled enough in my calendar app to pass the boundary I will get an undocumented crash. Is it possible to have a best effort result instead? I was testing my previous equinox calculator code against `-2000..10000` and it was working fine and I was just caring about its results I knew were true not caring about distant future. Thanks!

**Comment by cosinekitty** [comment]
Interesting! I will investigate this. Any time the code throws an `InternalError` exception, that is a bug that needs to be fixed.

**Comment by cosinekitty** [comment]
I reproduced the issue here. I believe the problem is I'm assuming the equinoxes and solstices happen within too narrow a range of calendar dates, and this is not true over longer spans of time. I'm adding a more robust unit test over a much wider span of years.
