### ISSUE TITLE
Kotlin: Use Time naming instead AstroTime

### ISSUE THREAD

**Issue by ebraminio** [cosinekitty/astronomy#196]
I saw Python port uses Time instead AstroTime https://github.com/cosinekitty/astronomy/blob/0c4e3df/generate/template/astronomy.py#L559 I don't know which way do you prefer more personally but at least in Kotlin / Java using Time won't clash with system things naming as far as I can say you if you prefer that also you can use `Time` in Kotlin port also (which I think I'm also more in favor of)

**Comment by ebraminio** [comment]
Oh same could be said about AstroVector to Vector, I like that naming also as the vector feels like just a regular one.

Yes, there is `java.util.Date`, `java.util.Calendar` and `java.time.*` which none have `Time` so it should be safe use that if you like the one in Python.

**Comment by cosinekitty** [comment]
OK, I like the idea for Vector also.

**Comment by cosinekitty** [comment]
I am renaming AstroVector and AstroTime, but it breaks the Java demo, and I don't know why:

```
don@spearmint:~/github/astronomy/demo/java $ ./gradlew jar

> Task :compileJava FAILED
/home/don/github/astronomy/demo/java/src/main/java/io/github/cosinekitty/astronomy/demo/Main.java:4: error: cannot find symbol
import io.github.cosinekitty.astronomy.Time;
                                      ^
  symbol:   class Time
  location: package io.github.cosinekitty.astronomy
/home/don/github/astronomy/demo/java/src/main/java/io/github/cosinekitty/astronomy/demo/Main.java:22: error: cannot find symbol
                    System.out.println(new Time(new Date()));
                                           ^
  symbol:   class Time
  location: class Main
```

It seems  like the script `demo/java/demotest` does not use the latest compiled version of the Kotlin code. Can you help me fix this?  I can try pushing the code anyway, even though it will fail the unit test, if that helps.

**Comment by cosinekitty** [comment]
I went ahead and pushed 57a736067a2ef005c05b30d94df08d46d78d5326. I believe it will fail the GitHub Actions tests, and maybe you can help me figure out what is wrong.

**Comment by ebraminio** [comment]
> It seems like the script demo/java/demotest does not use the latest compiled version of the Kotlin code.

For now it has one way, to first commit the change then use commit hash https://github.com/cosinekitty/astronomy/blob/kotlin/demo/java/build.gradle.kts#L15

`com.github.cosinekitty:astronomy:COMMIT_HASH`

**Comment by ebraminio** [comment]
Updated my app with the rename, fantastic, and filed the demo fix as a PR, thanks :)
