### ISSUE TITLE
Expose a planet's orbital period to the library

### ISSUE THREAD

**Issue by Alexbay218** [cosinekitty/astronomy#256]
Looking a the js library, it doesn't look like the orbital period is exposed. Being able to get the information from the library would be nice, since I've resorted to copying and pasting the planettable into my code.

**Comment by Alexbay218** [comment]
I'm using it for a game engine, which doesn't need precision. Maybe a disclaimer about the orbital period is good enough? If this doesn't quite fit the scope of the project, I understand. For me at least its only a convenience thing.

**Comment by cosinekitty** [comment]
That's cool! I will export the orbital periods then. I always like to ask why somebody wants something, because sometimes what they ask for turns out to be different from what they actually need.

**Comment by Alexbay218** [comment]
Awesome! Really impressed with how fast this got resolved!
