### ISSUE TITLE
Deno package support

### ISSUE THREAD

**Issue by jorjun** [cosinekitty/astronomy#263]
In my Deno project I can import like this:

`import { AstroTime, Seasons } from "https://cdn.skypack.dev/astronomy-engine?dts";
`

But no types are getting through..

Wonder if it would be straightforword to package here: https://deno.land/add_module

**Comment by cosinekitty** [comment]
The Node/Deno package side of things is very far outside my expertise. As a general idea, I would prefer to positively diagnose the issue before trying to fix it. If I understand correctly, there is something wrong with the TypeScript declarations not coming through for you in Deno, even though they should be included in the npm package. Can you provide some more details about the issue with types?

@matheo, can you provide some assistance with this one? It would be greatly appreciated... I don't know what to ask or how to approach this issue.

**Comment by matheo** [comment]
@cosinekitty it seems that `typings` field is not enough
maybe we need to rename it to `types` and that will fix the issue
https://docs.skypack.dev/package-authors/package-checks#types

I'm creating a PR ;)

**Comment by cosinekitty** [comment]
I just published Astronomy Engine v2.1.9 including the pull request from @matheo. I'm reopening the issue until @jorjun can confirm it really works. Please let us know whether this solves your issue in Deno.

**Comment by jorjun** [comment]
Thanks so much for rapid resolution. Yep, all good with the following import.

`import { Body, Ecliptic, GeoVector } from "https://esm.sh/v97/astronomy-engine@2.1.9"
`

**Comment by cosinekitty** [comment]
Thank you very much @matheo!  This was a huge help.

**Comment by matheo** [comment]
Thanks to you @cosinekitty for the great stuff!
