### ISSUE TITLE
Doubt about coordinate transformation.

### ISSUE THREAD

**Issue by ea3hmj** [cosinekitty/astronomy#269]
What is the best way to convert object Ra Dec j2000 to Topocentric coordinates of an observer at a time T.
I have tried this but there is a small error.
`Topocentric hor = Astronomy.Horizon(time, observer, raj2000, decj2000, Refraction.None);`

**Comment by cosinekitty** [comment]
How much error are you encountering? Can you provide the numeric values you are testing with, and what you expected the answer to be?

**Comment by ea3hmj** [comment]
Ra J2000 = 23h 56m 47.79s
Dec J2000=-1° 56' 52.5" 
I use 
time = new AstroTime(DateTime.UtcNow);  //21/11/2022 19:26:00
the result is:
az=172.8944 El=46.2548
I use 
time = new AstroTime(ddate.Year, ddate.Month, ddate.Day, ddate.Hour, ddate.Minute, ddate.Second); // 21/11/2022 19:26:00
the result is:
Az=173.0864 El=46.2669

I don't know where I'm going wrong.

**Comment by cosinekitty** [comment]
OK. And what are the latitude, longitude, and height above sea level you are using?

**Comment by ea3hmj** [comment]
Lat=41.5695334
Lon=2.013942
Alt=320m

**Comment by cosinekitty** [comment]
I'm not sure yet what is happening. When I try this...

```csharp
namespace CosineKitty
{
    static class Program
    {
        static void Calculate(AstroTime time)
        {
            var observer = new Observer(41.5695334, 2.013942, 320.0);
            double ra = 23.0 + 56.0/60.0 + 47.79/3600.0;
            double dec = -(1.0 + 56/60.0 + 52.5/3600.0);
            Topocentric hor = Astronomy.Horizon(time, observer, ra, dec, Refraction.None);
            Console.WriteLine($"az={hor.azimuth:F4}, alt={hor.altitude:F4}");
        }

        static int Main(string[] args)
        {
            Calculate(new AstroTime(2022, 11, 21, 19, 26, 0.0));

            var d = new DateTime(2022, 11, 21, 19, 26, 0, DateTimeKind.Utc);
            Calculate(new AstroTime(d));

            Calculate(new AstroTime(d.Year, d.Month, d.Day, d.Hour, d.Minute, d.Second));

            return 0;
        }
    }
}
```

I get this output:

```text
az=172.8927, alt=46.2547
az=172.8927, alt=46.2547
az=172.8927, alt=46.2547
```

There is some detail I am missing. Can you paste your exact C# code here?

**Comment by ea3hmj** [comment]
Sorry for the delay,

I have tried what you sent me and it works fine.

Thanks

**Comment by cosinekitty** [comment]
Did you figure out what the problem was?

**Comment by ea3hmj** [comment]
No, but it works now.

**Comment by cosinekitty** [comment]
OK, I'm glad to hear it is working for you.
