### ISSUE TITLE
How about support computing true solar time

### ISSUE THREAD

**Issue by hh-in-zhuzhou** [cosinekitty/astronomy#287]
Can this goal be achieved or can this be a goal ？

**Comment by cosinekitty** [comment]
As I think about this, it is not obvious what return value would be most helpful. Not only the time, but the calendar date, can be affected. Do you have an opinion about what would be most useful for what you need?

**Comment by cosinekitty** [comment]
To explain more about my question, the easiest answer I could calculate would be an hour value in the range $0 \le h \lt 24$, but without trying to figure out the date as a year, month, and calendar day.

The reason I don't want to calculate dates is that the code would need to understand things like the [International Date Line](https://en.wikipedia.org/wiki/International_Date_Line), a complicated shape that is a political structure, not a fact of nature. Even worse would be having to support time zones. That is why Astronomy Engine represents all times in UTC, and why it does not support local time.

To rephrase my question above, would having the value $h$ by itself be enough for a useful true solar time?

**Comment by hh-in-zhuzhou** [comment]
thanx very much. i want this to do some search on  calendar and astrology. also some curture things and history how people develop astronomy。the accuracy of your library is very good enough, it is awesome. 
i have read your problem. maybe it is not so comlex as you think, in my opinion , it only needs a UTC time，and local longtitude and latitude。the time difference of longtitude is easy to caculate. but i just don’t know how to caculate the time difference compensate，so i ask what if it can be a goal。if this can achived , i can help to achive.
for backward, can it surpport caculate time differene by local location? so we can ignore the international day line problem and political factor.
thans again! your work is great and very helpful

**Comment by cosinekitty** [comment]
Yes, I was thinking the same thing. I will make a function that calculates the true solar time for a given latitude, longitude, and UTC time. It will express the value in hours where 0 = solar midnight and 12 = solar noon. I'm glad the date line is not a concern.

**Comment by cosinekitty** [comment]
I just updated Astronomy Engine. Version 2.1.14 now includes a new function called HourAngle. You can use this to calculate true solar time. For example, see the demo program [solar_time.js](https://github.com/cosinekitty/astronomy/blob/master/demo/nodejs/solar_time.js). There are demos like this for all of the supported programming languages, not just JavaScript.
