### ISSUE TITLE
how to calculate ayanamsa (precession of equinoxes) 

### ISSUE THREAD

**Issue by vivekanand-rb** [cosinekitty/astronomy#291]
Trying to implement some astrology concept using this library in javascript. but there is no function to calculate  ayanamsa.

Reference: SWISS EPHEMERIS:  https://www.astro.com/swisseph/swisseph.htm
2.8.1.  The problem of defining the zodiac

sidereal planetary positions are usually computed from tropical positions using the equation:
sidereal_position = tropical_position – ayanamsha(t)
where ayanamsha is the difference between the two zodiacs at a given epoch.

**Comment by cosinekitty** [comment]
To clarify, are you asking for the change in longitude angle of the equinox points between two different years?

**Comment by vivekanand-rb** [comment]
yes

**Comment by cosinekitty** [comment]
OK, great! I created a demo program [vernal_point.js](https://github.com/cosinekitty/astronomy/blob/master/demo/nodejs/vernal_point.js)  that shows how you can do this. Here is an example of running it:

```
$ node vernal_point.js 1900-01-01 2000-01-01
time1 = 1900-01-01T00:00:00.000Z
time2 = 2000-01-01T00:00:00.000Z
The vernal point's ecliptic longitude changed by 1.3878 degrees.
```

**Comment by vivekanand-rb** [comment]
Thanks a lot @cosinekitty.
