### ISSUE TITLE
Detect polar day and polar night for Sun

### ISSUE THREAD

**Issue by BurgerZ** [cosinekitty/astronomy#313]
Is there any way to get the polar day/polar night information for Sun? `SearchRiseSet` returns AstroTime or null, so it will return the same result (null) for polar night and polar day, and it'd be great to differentiate those two situations.

Maybe something like this would be possible:
```typescript
export function SearchRiseSet(
    body: Body,
    observer: Observer,
    direction: number,
    dateStart: FlexibleDateTime,
    limitDays: number,
    metersAboveGround: number = 0.0
): AstroTime | SUN_UP | SUN_DOWN | null {

......
}
```

**Comment by cosinekitty** [comment]
Can you explain what you mean by *polar day* and *polar night*?

**Comment by BurgerZ** [comment]
Polar night - when the Sun is always up, the night lasts more than 24 hours (for example, for South Pole).
Polar day (midnight sun) - when the Sun is always up, and daylight is more than 24 hours long.

I ended up with my own implementation (I assume I understood things right):

```typescript
export function SearchRiseSet(
    body: Body,
    observer: Observer,
    direction: number,
    dateStart: FlexibleDateTime,
    limitDays: number,
    metersAboveGround: number = 0.0
): AstroTime | "ALWAYS_UP" | "ALWAYS_DOWN" | null {
    if (!Number.isFinite(metersAboveGround) || metersAboveGround < 0.0)
        throw `Invalid value for metersAboveGround: ${metersAboveGround}`

    // We want to find when the top of the body crosses the horizon, not the body's center.
    // Therefore, we need to know the body's radius.
    const body_radius_au: number = BodyRadiusAu(body)

    // Calculate atmospheric density at ground level.
    const atmos = Atmosphere(observer.height - metersAboveGround)

    // Calculate the apparent angular dip of the horizon.
    const dip = HorizonDipAngle(observer, metersAboveGround)

    // Correct refraction for objects near the horizon, using atmospheric density at the ground.
    const altitude = dip - REFRACTION_NEAR_HORIZON * atmos.density

    const angleHighest = SearchHourAngle(body, observer, 0, dateStart)
    const angleLowest = SearchHourAngle(body, observer, 12, dateStart)

    if (angleHighest.hor.altitude > 0.0 && angleLowest.hor.altitude > 0.0) {
        return "ALWAYS_UP"
    }

    if (angleHighest.hor.altitude < 0.0 && angleLowest.hor.altitude < 0.0) {
        return "ALWAYS_DOWN"
    }

    // Search for the top of the body crossing the corrected altitude angle.
    return InternalSearchAltitude(
        body,
        observer,
        direction,
        dateStart,
        limitDays,
        body_radius_au,
        altitude
    )
}
```

**Comment by cosinekitty** [comment]
If you are happy with your solution, that is great. Or if you would rather not have to change Astronomy Engine code, have you tried passing a larger value for `limitDays`? For example, if `limitDays` is 370, `SearchRiseSet` will always find a sunrise or sunset, no matter where you are on the Earth or what time of year it is. Search for both sunrise and sunset, and whichever happens first tells you whether you started at night or day. In other words, both calls return `AstroTime`, and you can compare the numeric `ut` field inside them to see which is the smaller number.

**Comment by cosinekitty** [comment]
As another thought, you can still use `limitDays = 1`, but if `SearchRiseSet` returns null, call `Horizon` as shown [in this demo line](https://github.com/cosinekitty/astronomy/blob/63ed3746b224ef6f130debd2a65740d154036aee/demo/nodejs/positions.js#L62) for the Sun to see if it as above or below the horizon at the start time. That tells you whether the search start time is happening in day or night.

**Comment by BurgerZ** [comment]
Makes sense, thanks for the details! I think I'm good with your solution.
