### ISSUE TITLE
Integration to home assistant

### ISSUE THREAD

**Issue by Greg50100** [cosinekitty/astronomy#319]
Hi there,

Thank you for sharing your work with us. I discovered the world of astronomy with your web pages.
I would like to integrate your work into home assistant but I do not have the necessary knowledge to do so.
Is it possible to have some help integrating the npm package with node-red in home assistant.
Or if possible to integrate the python script directly into home assistant?

**Comment by Greg50100** [comment]
Unfortunately I don't know anyone to help me. Is it possible to keep this topic open for a while, in case anyone has an idea.
I'll keep digging to find a solution that I'll share here.

**Comment by Greg50100** [comment]
with the help of the node red forum here is the solution for in home assistant. All that is missing are the sensors to add.

https://discourse.nodered.org/t/using-npm-module/81977

If interested, I could, in the future, share more accomplished work

**Comment by cosinekitty** [comment]
@Greg50100 I would love to see whatever you come up with!
