### ISSUE TITLE
how to add planet ceres in astronomy.js?

### ISSUE THREAD

**Issue by testori1972** [cosinekitty/astronomy#349]
I want to modify astronomy.js and astronomy.ts, I want to know how to calculate the planet Ceres and what various websites?

**Comment by cosinekitty** [comment]
There is probably an algorithm for the 4 major asteroids somewhere. I would start by looking at Stellarium to see how they do it.

**Comment by testori1972** [comment]
Yes, don't forget to include a tutorial on how to calculate the formula for 4 asteroid bodies so you can make more planetary bodies, and now I have to learn a lot about Blender to render to ThreeJS then render to HTML, CSS and JS
