### ISSUE TITLE
moving and modifying scripts to new scripts

### ISSUE THREAD

**Issue by testori1972** [cosinekitty/astronomy#355]
because the vsop model is not suitable for calculating planets, we created a separate script but with the same name, namely "astronomy.js" so I just want to move all assets such as galaxies, rotation matrices, vectors, etc. to a new script without vsop 87 but that's not enough because we use a lot of vendor data such as stellarium etc. from other people on github to be able to calculate the planets completely, I hope you have permission

**Comment by cosinekitty** [comment]
That sounds fine. Astronomy Engine is provided under the [MIT license](https://github.com/cosinekitty/astronomy/blob/master/LICENSE), which is very permissive in how you use the code.

**Comment by matheo** [comment]
@testori1972 is your modification private or you will release the full-pack?
