### ISSUE TITLE
Add a mission statement to README.

### ISSUE THREAD

**Issue by cosinekitty** [cosinekitty/astronomy#50]
Document why this project was created. Tell the story of how I started out trying to translate NOVAS directly to JavaScript and discovered it requires large ephemeris files.

Document project goals:
- Reliable and well-tested.
- Easier for programmers who are not professional astronomers to understand and use.
- Small and efficient code within 1 arcminute precision.
- Focused on use in amateur astronomy, calendars, etc.

**Comment by matheo** [comment]
Oh wow, I feel lucky today that I found our job!
Thank you very very much because this API is what I've been dreaming about!
I will find some spare time to play with this engine and contribute with ideas
and ask some questions to get decent astronomy knowledge as well :)
