### ISSUE TITLE
Decouple the ephemeris data from the code

### ISSUE THREAD

**Issue by astroanu** [cosinekitty/astronomy#63]
Really good library. ! 
Is it possible to decouple the ephemeris data from the code?

**Comment by cosinekitty** [comment]
Thank you for your kind words. Can you explain more what you are trying to do? What about the existing design is causing a problem?

**Comment by cosinekitty** [comment]
Hi again, @astroanu ... I'm checking to see if you found a solution to your problem. I'm still not clear on what you are looking for.

**Comment by astroanu** [comment]
Hi, sorry. was a bit busy and forgot all about this.

I was just experimenting with horizons data and i thought having ephemeris data downloaded from horizons and run against your script would be a good feature. But i see that the intention of this project is more about having run in the browser as a non-dependant script, so my request might not align correctly with the project goal. :)

**Comment by cosinekitty** [comment]
Oh, OK. I use ephemeris data as a part of the build process for all four supported languages (JavaScript, C, C#, and Python). The build uses NOVAS C 3.1 with DE405 ephemeris data to verify all calculations. There are also some unit test data files I created using JPL Horizons. If someone is just using Astronomy Engine in another project, they don't need the ephemeris. Anyone who develops on Astronomy Engine needs to run the build process, which downloads the 54 MB ephemeris file as a foundation for the code generator and unit tests.

**Comment by astroanu** [comment]
oh , now i understand. thanks for the clarification. ! :)
