### ISSUE TITLE
Dont see any installation steps to run demo here.

### ISSUE THREAD

**Issue by vasuneet** [cosinekitty/astronomy#75]
Dont see any installation steps to run demo here.

**Comment by cosinekitty** [comment]
Hi @vasuneet . Yes, I should write some instructions. Perhaps I can help you get started. Which of the 4 supported programming languages are you interested in starting with?

**Comment by vasuneet** [comment]
I made browser folder as a root folder to test this and replaced astromomy.js from src folder. now it worked but i wanted to make sure calculations are working fine.But it seems little bit different. For instance : -
I provide the following Data: 
Date :  Actual Date i wanted to enter 8-Feb-1976 (GMT+5:30) but in javascript it is not feasible. So i hardcoded the following converted UTC value 
1976-02-07 23:40:00
longitude/lattitude : 29.4727° N, 77.7085° E
showing following data : 

body | RA | DEC | Az | Alt
-- | -- | -- | -- | --
Sun | 21.42 | -15.15 | 330.08 | -73.17
Moon | 2.91 | 16.49 | 283.92 | 8.88
Mercury | 19.75 | -19.35 | 58.52 | -71.53
Venus | 19.17 | -21.89 | 76.38 | -65.76
Mars | 5.04 | 25.68 | 279.80 | 39.72
Jupiter | 1.30 | 7.01 | 288.21 | -15.71
Saturn | 8.04 | 20.81 | 233.38 | 75.66
Uranus | 14.35 | -13.53 | 105.34 | 0.19
Neptune | 16.85 | -20.98 | 95.40 | -35.21
Pluto | 13.18 | 11.17 | 92.47 | 27.29

While expected data is the following one  


Planet	Degree
Sun		25.06302858999169
Moon	23.039739111514784	
Mars	23.16728192913189	
Mercury	0.8537759881635907	
Jupiter	26.7932951265567	
Venus	22.378024540371996	
Saturn	4.493266132479931	
Rahu	23.71582972007326	
Ketu	23.71582972007326	
Ascendant 18.158853300793325

**Comment by cosinekitty** [comment]
OK, I see there is a bug in that demo I need to fix.  The script in `positions.html` is throwing an exception, so the numbers are not updating in real time like they are supposed to.  I will post another message here after I have fixed it.

Just for clarification, when you have the line

```
Sun 25.06302858999169
```

What kind of coordinate system is that number expressed in? Astronomy Engine supports multiple angular coordinate systems:

- ecliptic: latitude and longitude
- equatorial: right ascension and declination
- horizontal: altitude and azimuth

I want to make sure I understand what you are trying to calculate.

**Comment by cosinekitty** [comment]
I want to thank you very much for this report. It helped me fix several problems:

- The `positions.html` demo was broken because my automated tests don't check the browser-based projects. I fixed the exception that was causing the page to stop working.

- I added a checkbox in `positions.html` that allows you to optionally enter a date and time manually, instead of using the computer's clock. You will not need to hardcode the date and time anymore. Just uncheck the box labeled "Automatic" and enter the date and time right in the web page.

- The relative links to `astronomy.js` and `astronomy.py` from the demo directories don't work in Windows like they do in Linux (where I do most of my development). So I have replaced the links with redundant copies of the files in the same directory where they are used. This uses a little extra disk space but it ensures that everything works on Windows from the very beginning.

I hope you will try again using the latest code and let me know how it works.

**Comment by vasuneet** [comment]
thanks. i will check it again.

**Comment by vasuneet** [comment]
Let me understand , when you are saying i can enter the date manually. i can just fill the actual date and time and based on long/lat you will be able to convert this automatically.

**Comment by vasuneet** [comment]
I uncheked the box and filled the date manually . Its showing nothing but if i refresh the page then it shows the data with converted date.[](
![issue](https://user-images.githubusercontent.com/3884434/91230754-ad773900-e6f1-11ea-83d8-8687b3a7694f.png)

**Comment by vasuneet** [comment]
![issue](https://user-images.githubusercontent.com/3884434/91230826-d5ff3300-e6f1-11ea-8be6-bc414d1aacb1.png)

**Comment by cosinekitty** [comment]
The date you show, 1976-02-76, is not a valid date. That is why it doesn't show anything. As soon as you enter something JavaScript can parse as a valid date and time, it will show the table of body locations.

**Comment by vasuneet** [comment]
oh its my bad. let me check again

**Comment by vasuneet** [comment]
So where i can found documentation about getting different coordinate system:

ecliptic: latitude and longitude
equatorial: right ascension and declination
horizontal: altitude and azimuth
I want to make sure I understand what you are trying to calculate.

**Comment by cosinekitty** [comment]
[This section](https://github.com/cosinekitty/astronomy/tree/master/source/js#coordinate-transforms) of the documentation talks about the 4 coordinate systems supported.

As an introduction:

- Ecliptic (ECL) uses the mean plane of the Earth's orbit as a reference. The x-axis points from the Sun toward where the Earth was at the March 2000 equinox. The y-axis points in the same plane toward the June 2000 solstice. The z-axis points in the perpendicular direction that is more North than South (it is 23.5 degrees away from the celestial north pole).

- Equatorial uses the plane of the Earth's equator. There are two kinds:
    - Equatorial of date (EQD) uses the Earth's equator as at the date and time of the observation. This is because the Earth's axis is always changing (precession and nutation).
    - J2000 equatorial (EQJ) uses the Earth's equator as it was on January 1, 2000.
    - Equatorial coordinates can be given in rectangular form (x, y, z) or in angular form (RA, DEC).
        - The equatorial x-axis is exactly the same as in the ecliptic system.
        - The equatorial y-axis is 90 degrees counterclockwise from the x-axis, as seen looking down onto the Earth's north pole, also in the plane of the Earth's equator.
        - The equatorial z-axis points in the same direction as a line going from the center of the Earth out through the Earth's north pole.
    - When measured using angles, the following are used: 
        - right ascension (RA) is like longitude, but is measured in sidereal hours, going from 0 to 24 around the projection of the Earth's equator onto the sky.
        - declination (DEC) is like latitude projected onto the sky. It goes from -90 degrees at the south celestial pole to +90 degrees at the north celestial pole.

- And finally, horizontal (HOR) uses the sky as seen by an observer at a particular location on the Earth's surface.
    - Azimuth is the compass direction around the apparent horizon, with 0 degrees = North, 90 = East, 180 = South, 270 = West.
    - Altitude is the angle above or below the horizon. An altitude of 0 means the object is on the horizon. If it is +90 degrees, it is straight up. An object with a negative altitude is not visible to that observer because it is below the horizon.

I hope this helps!
