### ISSUE TITLE
Astronomy.SearchLunarEclipse(date) appears to fail in for a few days in December

### ISSUE THREAD

**Issue by thenaterhood** [cosinekitty/astronomy#78]
Ran into this one this week. SearchLunarEclipse is failing for me with "Cannot find full moon." for the date Fri Dec 18 2020 12:17:04 GMT-0500 (Eastern Standard Time).

I was able to work around this by catching the exception, adding a month to the date, and trying again.

Little bit of trial and error, it looks like this is failing between (in eastern time) roughly:
December 16, 17:00 and December 20, 02:00

**Comment by cosinekitty** [comment]
Thanks for the report! I will investigate.

**Comment by cosinekitty** [comment]
Hi Nate, I was able to reproduce the issue you mentioned with new unit tests I added for all 4 supported languages (C, C#, Python, and JavaScript). I believe the changes I pushed in 246ac47d2b07a8f72d86d066fece46c2f5972d04 fix this problem. 

The diagnosis: when it searches for a full moon, Astronomy Engine does a quick approximation of when the full moon will occur. Then it searches near that approximate time for the exact moment of the full moon. My search window was large enough for all of my existing unit tests, but not for the date ranges you tried. I increased the window size from 1.8 days to 3.0 days. The failure case you found fell just a couple of hours outside that 1.8 day window.

Would you please try pulling the latest code and let me know whether it is working for you now?

**Comment by thenaterhood** [comment]
Hey Don! Figures, right, just a near miss :)

Yeah, looks good to me now. Thanks!

**Comment by cosinekitty** [comment]
OK, good. Thanks again for the bug report.
