### ISSUE TITLE
JS: Eliminate redundant functions `MakeObserver` and `MakeSpherical`.

### ISSUE THREAD

**Issue by cosinekitty** [cosinekitty/astronomy#86]
In the TypeScript/JavaScript code, the functions `MakeObserver` and `MakeSpherical` are no longer needed, because the classes `Observer` and `Spherical` are now exported, along with their constructors. These functions are just pass-throughs for the constructors. I would like to get rid of them, and rework the existing demos to just do `new Observer(...)` and `new Spherical(...)`.

@matheo : Will this break your demo at https://matheo.github.io/astronomy/#/demos/body-positions ? Should I hold off on this change, or can I go ahead and do it?

**Comment by matheo** [comment]
@cosinekitty fell free to refactor, I will update the `body-positions` component when you finish.
The old website compilation will keep working in Github Pages.
A website sync would be required if Netlify does a compilation with the latest code ;)
