### ISSUE TITLE
Calculate the tilt of a sunlit body as seen by an observer on the Earth

### ISSUE THREAD

**Issue by cosinekitty** [cosinekitty/astronomy#90]
Given a time, a body (the moon or a planet), and the location of an observer on the Earth, calculate the orientation of the apparent sunlit side of that body as seen by the observer. This is a "tilt angle" clockwise from the local zenith as the observer faces the azimuth of the body.

I will need to experiment with the JPL Horizons tool to see if it can provide test data for me.

**Comment by cosinekitty** [comment]
I am generalizing this feature to include functions to pivot any rotation matrix around a given axis by a given angle. Then developers will be able to rotate from horizontal (HOR) coordinates to an arbitrary camera orientation. From that orientation, it will be simple to calculate the tilt angle of the sunlit side of an observed body. Stay tuned!

**Comment by cosinekitty** [comment]
This work was completed in a series of commits ending with 090c71797887268ac4cb2028bba3bf5153a44865, resulting in npm package `astronomy-engine@2.0.2`, tagged as [npm_2.0.2](https://github.com/cosinekitty/astronomy/releases/tag/npm_2.0.2). There are two new functions `IdentityMatrix` and `Pivot` in all four supported programming languages.

**Comment by programmer24601** [comment]
@cosinekitty can you give an example of how to use this?

I'm wanting to correctly orient the moon on a (north-is-up) stereographic map. I'm currently able to plot the moon + phase, just struggling to orient it.

**Comment by cosinekitty** [comment]
Try looking in the demo folder for the programming language you are interested in. There are example programs called "camera.c", "camera.py", etc. These should be very close to what you are looking for. They calculate the tilt angle of the Moon's illuminated face relative to an observer's horizon. Please let me know whether this helps or not.

**Comment by mh1622** [comment]
Hi @cosinekitty I've only recently been able to work on this. Your solution is very close to what I need, however, my stereographic map projection means that the observer's horizon is circular with a fixed "north-is-up" orientation. I think therefore that the moon's azimuth needs subtracting from the "tilt angle of the sunlit side" output from the Camera() function (or possibly equivalently fixing the first pivot to a particular cardinal direction, so we're not "facing the moon's azimuth"). I can't seem to get it right though when comparing with Stellarium.

Any help would be very much appreciated :slightly_smiling_face:

**Comment by cosinekitty** [comment]
@mh1622 I think you are on the right track. Wherever you see a reference in the code to the Moon's azimuth, replace that azimuth with whatever azimuth you want to face. You can do the same thing with substituting your desired amount of tilt with the Moon's tilt angle.

**Comment by mh1622** [comment]
Yes that's correct. Right now I'm trying to adjust the Camera function's tilt angle output after the fact by subtracting the moon's azimuthal angle (with limited success, i.e. correct in some quadrants of the sky, incorrect in others). It'd be more elegant to perform these matrix transformations directly, but I'm having difficulty mentally picturing these transformations.

**Comment by cosinekitty** [comment]
OK, I thought about it a little more. This is a really rough idea but I hope it helps. If you can calculate where the Sun is, then the lit side of the Moon is pointing toward the Sun. Therefore, if you can calculate the projection of the Sun (whether above or below the horizon) onto your horizon disc, and then "aim" the lit side of the Moon toward that point, I think you will get good results.

**Comment by programmer24601** [comment]
I figured it out. I went with the first approach (`tilt - azimuth`), but realised that due to the way I was drawing the moon phase, the orientation would end up 180° out, depending on whether the moon's waxing or waning.

```
  const phase = MoonPhase(dateTime) / 360;
  const phaseCorrection = phase > 0.5 ? -degToRad(180) : 0;
  const correctedTilt = tilt - degToRad(moon_hor.azimuth) + phaseCorrection;
  const normalizedTilt = normalize(correctedTilt); // returns angle to 0-360° range
```

Thanks again for the help, astronomy-engine is awesome :+1:
